version: 2.1
orbs:
  python: circleci/python@2
jobs:
  install-dependencies:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            if [ -f "package.json" ]; then
              npm install
            elif [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi
workflows:
  install-dependencies-workflow:
    jobs:
      - install-dependencies