version: 2.1
orbs:
  python: circleci/python@2
jobs:
  install-dependencies:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs npm
      - run:
          name: Install dependencies
          command: |
            if [ -f "package.json" ]; then
              npm install
            elif [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi
workflows:
  install-dependencies-workflow:
    jobs:
      - install-dependencies